const ADD_TODO = 'ADD_TODO';
const DELETE_TODO = 'DELETE_TODO';
const CHANGE_TODO = 'CHANGE_TODO';
const CLEAR_LIST = 'CLEAR_LIST';
const SHOW_TODO = 'SHOW_TODO';
const SAVE_TODO = 'SAVE_TODO';

export {ADD_TODO, DELETE_TODO, CHANGE_TODO, CLEAR_LIST, SHOW_TODO, SAVE_TODO}